// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qkcwggyjouonkgeusskn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFrY3dnZ3lqb3VvbmtnZXVzc2tuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExODc2ODYsImV4cCI6MjA2Njc2MzY4Nn0.Z5IT-MpL2oJZ8vRJh_TTIALR_1ucFY8Qb90q18d6Frs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);